### ISSUE TITLE
Friend finder

### ISSUE THREAD

**Issue by JasonMan34** [sbarrack/skribbl-community-scripts#33]
* List of friends to stop when one of the conditions is met
* (Maybe?) Score filter to find lobbies with good players

**Comment by sbarrack** [comment]
This feature is already provided by Skribbl Typo and another script by jancc that is licensed. Recommend using one of those to avoid this script having similarities to licensed code which could be considered an infringement.

**Comment by sbarrack** [comment]
Functionality exists in the Christian Skribbl finder script and Skribbl Typo
